# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MapThemeManager
                                 A QGIS plugin
 テーマ編集プラグイン作成
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        copyright            : (C) 2023 orbitalnet
 ***************************************************************************/

 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MapThemeManager class from file MapThemeManager.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .map_theme_manager import MapThemeManager
    return MapThemeManager(iface)
